export const environment = {
  production: true,
  COINAPI_URL: process.env['NG_APP_COINAPI_URL'],
  COINAPI_KEY: process.env['NG_APP_COINAPI_KEY'],
  API_BASE_URL: process.env['NG_APP_API_BASE_URL'],
  NOTIFICATIONS_API_BASE_URL: process.env['NG_APP_NOTIFICATIONS_API_BASE_URL'],
  COINMARKETCAP_BASE_URL: process.env['NG_APP_COINMARKETCAP_BASE_URL'],
  COINMARKETCAP_API_KEY: process.env['NG_APP_COINMARKETCAP_API_KEY'],
}